version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sellify-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sellify_platform
      POSTGRES_USER: sellify_admin
      POSTGRES_PASSWORD: sellify_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sellify_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
